version: '3.8'

services:
  backend:
    image: lensgo
    pull_policy: never
    container_name: lensgo
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  